Repository MessagePack-CSharp/MessagePack-CSharp, pull requests merged in 2019-11, with the labels that each got.

#609 Add fast path for reading consecutive strings/byte arrays
  README.md
  sandbox/PerfBenchmarkDotNet/GeneratedFormatter.cs
  sandbox/Sandbox/Generated.cs
  src/MessagePack.GeneratorCore/Generator/FormatterTemplate.cs
  src/MessagePack.GeneratorCore/Generator/FormatterTemplate.tt
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Formatters/StandardClassLibraryFormatter.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Formatters/TypelessFormatter.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Internal/CodeGenHelpers.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackReader.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Resolvers/DynamicObjectResolver.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/MessagePackBinaryTest.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/MessagePackReaderTests.cs
  src/MessagePack.UniversalCodeGenerator/Generator/FormatterTemplate.cs
  src/MessagePack.UniversalCodeGenerator/Generator/FormatterTemplate.tt
  src/MessagePack.UniversalCodeGenerator/Utils/RoslynExtensions.cs
  src/MessagePack.UniversalCodeGenerator/publish.bat
  src/MessagePack/PublicAPI.Unshipped.txt
Labels: enhancement

#608 Offer MessagePackSerializerOptions to collection deserializers
  src/MessagePack.ImmutableCollection/Formatters.cs
  src/MessagePack.ReactiveProperty/Formatters.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Formatters/CollectionFormatter.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Formatters/DictionaryFormatter.cs
  src/MessagePack/PublicAPI.Unshipped.txt
Labels: blocker, enhancement

#627 Throw MessagePackSerializationException instead of IOE
  src/MessagePack.Internal/MessagePack.Internal.csproj
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Formatters/CollectionFormatter.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Formatters/DictionaryFormatter.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Formatters/MultiDimensionalArrayFormatter.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Formatters/PrimitiveObjectFormatter.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Formatters/StandardClassLibraryFormatter.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Formatters/UnsafeBinaryFormatters.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Internal/AutomataDictionary.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Internal/GuidBits.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Internal/TinyJsonReader.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/LZ4/LZ4Codec.Safe.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/LZ4/LZ4Codec.Unsafe.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackReader.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackSerializationException.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackSerializer.Json.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackSerializerOptions.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Resolvers/ContractlessReflectionObjectResolver.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Resolvers/DynamicObjectResolver.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/T4/TupleFormatter.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/T4/ValueTupleFormatter.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/MessagePackReaderTests.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/T4/MessagePackReaderTests.ReadInt.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/Shims/XUnit.cs
  src/MessagePack/Formatters/TupleFormatter.cs
  src/MessagePack/Formatters/TupleFormatter.tt
  src/MessagePack/Formatters/ValueTupleFormatter.cs
  src/MessagePack/Formatters/ValueTupleFormatter.tt
  tests/MessagePack.Tests/MessagePackReaderTests.ReadInt.cs
  tests/MessagePack.Tests/MessagePackReaderTests.ReadInt.tt
Labels: blocker

#633 Ensure that only documented exceptions are thrown
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackSerializer.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Resolvers/DynamicObjectResolver.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/MessagePackSerializerTypelessTests.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/ObjectResolverTest.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/PrimitivelikeFormatterTest.cs
Labels: blocker

#632 Add MessagePackReader.ReadRaw()
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackReader.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/MessagePackReaderTests.cs
  src/MessagePack/PublicAPI.Unshipped.txt
Labels: enhancement

#636 Remove Nerdbank.Streams again
  src/MessagePack.UnityClient/Assets/Editor/PackageExport.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Internal/Sequence`1.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/_InternalVisibleTo.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/Tests.asmdef
  src/MessagePack.UnityClient/Assets/TempRuntimeUnitTestScene_1566454945.unity
  src/MessagePack.UnityClient/copy_assets.bat
  src/MessagePack.UnityClient/copy_assets.sh
  src/MessagePack/MessagePack.csproj
Labels: blocker

#649 Add v1->v2 migration doc
  README.md
  doc/migration.md
Labels: enhancement

#648 Move extension type codes
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Formatters/TypelessFormatter.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackCode.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackSerializer.Json.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackSerializer.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/ThisLibraryExtensionTypeCodes.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/UnityShims/Extension/UnsafeBlitFormatter.cs
  src/MessagePack.UnityShims/MessagePack.UnityShims.csproj
  src/MessagePack/PublicAPI.Unshipped.txt
  tests/MessagePack.Tests/ExtensionTests/LZ4Test.cs
  tests/MessagePack.Tests/MessagePack.Tests.csproj
Labels: blocker, enhancement

#663 Stream deserialization fixes
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackReader.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackSerializer.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackWriter.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/MessagePackReaderTests.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/MessagePackSerializerTest.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/Shims/XUnit.cs
Labels: blocker

#669 Fix nuget package ID for mpc tool back to `MessagePack.Generator`
  src/MessagePack.Generator/MessagePack.Generator.csproj
Labels: blocker

#677 API support for multiple compression schemes
  benchmark/SerializerBenchmark/Serializers/MessagePackSerializer.cs
  sandbox/DynamicCodeDumper/DynamicCodeDumper.csproj
  sandbox/PerfNetFramework/Program.cs
  sandbox/Sandbox/Program.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackCompression.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackSerializer.Json.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackSerializer.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackSerializerOptions.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/MessagePackSerializerOptionsTests.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/ToJsonTest.cs
  src/MessagePack/PublicAPI.Unshipped.txt
  tests/MessagePack.AspNetCoreMvcFormatter.Tests/AspNetCoreMvcFormatterTest.cs
  tests/MessagePack.Tests/ExtensionTests/LZ4Test.cs
Labels: blocker, enhancement

#681 Add Compression.LZ4ContiguousBlock and implementation
  sandbox/PerfBenchmarkDotNet/Lz4Benchmark.cs
  sandbox/PerfBenchmarkDotNet/Lz4PrimitiveBenchmark.cs
  sandbox/PerfBenchmarkDotNet/PerfBenchmarkDotNet.csproj
  sandbox/PerfBenchmarkDotNet/Program.cs
  sandbox/PerfBenchmarkDotNet/StringKeySerializerTarget2.cs
  sandbox/Sandbox/Program.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackCompression.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackSerializer.Json.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackSerializer.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/ThisLibraryExtensionTypeCodes.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/Loader.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/LZ4Test.cs
  src/MessagePack/PublicAPI.Unshipped.txt
  tests/MessagePack.Tests/ExtensionTests/LZ4Test.cs
Labels: enhancement

#690 Fix CreatePeekReader so it's truly equivalent to the original
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackReader.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/MessagePackReaderTests.cs
Labels: enhancement

#687 Remove formatter instance cache from TypelessFormatter
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Formatters/TypelessFormatter.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Resolvers/TypelessContractlessStandardResolver.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Resolvers/TypelessObjectResolver.cs
  src/MessagePack/PublicAPI.Unshipped.txt
Labels: blocker
