Repository MessagePack-CSharp/MessagePack-CSharp, pull requests merged in 2019-10, with the labels that each got.

#589 Remove mutable fields/properties from TypelessFormatter
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Formatters/TypelessFormatter.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackSerializer.Json.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackSerializerOptions.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackWriter.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/MessagePackSerializerOptionsTests.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/MessagePackSerializerTypelessTests.cs
Labels: blocker

#595 Apply vs-threading analyzers and fix issues they found
  Directory.Build.props
  MessagePack.ruleset
  src/MessagePack.AspNetCoreMvcFormatter/MessagePackInputFormatter.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackSerializer.NonGeneric.cs
  src/MessagePack.UniversalCodeGenerator/CodeAnalysis/TypeCollector.cs
  src/MessagePack.UniversalCodeGenerator/MessagePack.UniversalCodeGenerator.ruleset
  src/MessagePack.UniversalCodeGenerator/Program.cs
  src/MessagePack.UniversalCodeGenerator/Utils/ProcessUtil.cs
  src/MessagePack.UniversalCodeGenerator/Utils/RoslynExtensions.cs
  src/MessagePackAnalyzer/MessagePackCodeFixProvider.cs
  tests/MessagePack.Tests/MessagePack.Tests.ruleset
Labels: enhancement

#594 Add CancellationToken parameters to synchronous Stream (de)serialize methods
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackSerializer.NonGeneric.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackSerializer.cs
Labels: blocker, enhancement

#582 Improve compatibility with existing types
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Resolvers/DynamicObjectResolver.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/ContractlessStandardResolverTest.cs
  tests/MessagePack.Tests/ContractlessStandardResolverConstructorTests.cs
  tests/MessagePack.Tests/Utils/ChainingAssertion.Xunit.cs
Labels: enhancement

#603 Add CancellationToken to reader/writer structs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Formatters/CollectionFormatter.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Formatters/DictionaryFormatter.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Formatters/MultiDimensionalArrayFormatter.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackReader.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackSerializer.Json.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackSerializer.NonGeneric.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackSerializer.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackWriter.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/MessagePackReaderTests.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/MessagePackWriterTests.cs
  src/MessagePack/MessagePackSerializer+Typeless.cs
  src/MessagePack/PublicAPI.Unshipped.txt
Labels: enhancement
