Repository MessagePack-CSharp/MessagePack-CSharp, pull requests merged in 2020-09, with the labels that each got.

#1027 Add `ReadOnlyMemory<T>` and `ReadOnlySequence<T>` support
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Formatters/CollectionFormatter.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Resolvers/BuiltinResolver.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Resolvers/DynamicGenericResolver.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/CollectionTest.cs
  src/MessagePack/PublicAPI.Unshipped.txt
Labels: enhancement

#1029 Merge immutable collections formatters into main library
  README.md
  src/MessagePack.ImmutableCollection/AssemblyInfo.cs
  src/MessagePack.ImmutableCollection/MessagePack.ImmutableCollection.csproj
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Resolvers/StandardResolver.cs
  src/MessagePack.UnityClient/copy_assets.bat
  src/MessagePack/Formatters/ImmutableCollectionFormatters.cs
  src/MessagePack/MessagePack.csproj
  src/MessagePack/PublicAPI.Unshipped.txt
  src/MessagePack/Resolvers/ImmutableCollectionResolver.cs
  tests/MessagePack.Tests/ExtensionTests/ImmutableCollectionTest.cs
  tests/MessagePack.Tests/ExtensionTests/LZ4Test.cs
  tests/MessagePack.Tests/ExtensionTests/WithImmutableDefaultResolver.cs
Labels: enhancement

#1041 Use `Array.Empty<T>()` instead of `new T[]` wherever possible
  README.md
  src/MessagePack.ImmutableCollection/Formatters.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Formatters/CollectionFormatter.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Formatters/DateTimeFormatters.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Formatters/PrimitiveObjectFormatter.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Formatters/StandardClassLibraryFormatter.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Internal/AutomataDictionary.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/T4/ForceSizePrimitiveFormatter.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/T4/PrimitiveFormatter.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/FormatterTest.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/GenericFormatters.cs
  src/MessagePack/Formatters/ForceSizePrimitiveFormatter.cs
  src/MessagePack/Formatters/ForceSizePrimitiveFormatter.tt
  src/MessagePack/Formatters/PrimitiveFormatter.cs
  src/MessagePack/Formatters/PrimitiveFormatter.tt
  src/MessagePackAnalyzer/Utils/ConfigurationLoader.cs
Labels: enhancement

#1048 Fix handling nested generic types in code generation
  src/MessagePack.GeneratorCore/CodeAnalysis/Definitions.cs
  src/MessagePack.GeneratorCore/CodeAnalysis/TypeCollector.cs
  src/MessagePack.GeneratorCore/CodeGenerator.cs
  tests/MessagePack.Generator.Tests/GenerateGenericsFormatterTest.cs
Labels: mpc

#1061 Allow ctor parameter types to be anything assignable from their associated members
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Resolvers/DynamicObjectResolver.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/DynamicObjectResolverInterfaceTest.cs
Labels: enhancement

#1054 Enable deserialization constructors to use parameter names that match their property names
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Resolvers/DynamicObjectResolver.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/DynamicObjectResolverConstructorTest.cs
Labels: enhancement

#1063 Fix support of custom implementation of ICollection<T>
  README.md
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Formatters/CollectionFormatter.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Resolvers/DynamicGenericResolver.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/CollectionTest.cs
  src/MessagePack/PublicAPI.Unshipped.txt
Labels: enhancement

#1064 DynamicObjectTypeFallbackFormatter prioritize PrimitiveObjectFormatter to keep primitive type
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Formatters/DynamicObjectTypeFallbackFormatter.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Formatters/PrimitiveObjectFormatter.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/DynamicObjectFallbackTest.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/NonGenericCollectionTest.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/PrimitiveResolverTest.cs
Labels: enhancement

#1068 Merge master into v2.2
  README.md
  src/MessagePack.GeneratorCore/CodeAnalysis/Definitions.cs
  src/MessagePack.GeneratorCore/CodeAnalysis/TypeCollector.cs
  src/MessagePack.GeneratorCore/CodeGenerator.cs
  src/MessagePack.GeneratorCore/Generator/FormatterTemplate.cs
  src/MessagePack.GeneratorCore/Generator/FormatterTemplate.tt
  src/MessagePack.GeneratorCore/Generator/StringKey/StringKeyFormatterTemplate.cs
  src/MessagePack.GeneratorCore/Generator/StringKey/StringKeyFormatterTemplate.tt
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackSerializerOptions.cs
  src/MessagePack.UnityClient/Assets/Scripts/MessagePack/Resolvers/DynamicObjectResolver.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/DynamicObjectResolverConstructorTest.cs
  src/MessagePack.UnityClient/Assets/Scripts/Tests/ShareTests/DynamicObjectResolverInterfaceTest.cs
  tests/MessagePack.Generator.Tests/GenerateGenericsFormatterTest.cs
Labels: blocker
